//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Dialog2.rc 使用
//
#define IDD_DIALOG_MAIN                 101
#define MY_ICON_HOUSE                   106
#define IDD_DIALOG_PE                   107
#define IDD_DIALOG_SECTION              109
#define IDD_DIALOG_CONTENT              111
#define IDD_DIALOG_EXPORTTABLE          115
#define IDD_DIALOG_IMPORTTABLE          117
#define IDD_DIALOG_RELOCATETABLE        119
#define IDD_DIALOG_ADDSHELL             121
#define IDD_DIALOG_INPUTNAME            123
#define IDC_STATIC1                     1001
#define IDC_STATIC2                     1002
#define IDC_BUTTON_PE                   1003
#define IDC_STATIC9                     1003
#define IDC_BUTTON_ABOUT                1004
#define IDC_STATIC10                    1004
#define IDC_BUTTON_EXIT                 1005
#define IDC_LIST_PROCESS                1006
#define IDC_LIST_MODULE                 1007
#define IDC_BUTTON_SECTION              1008
#define IDC_BUTTON_CONTENT              1009
#define IDC_BUTTON_PE_EXIT              1010
#define IDC_BUTTON_SECTION_EXIT         1011
#define IDC_BUTTON_CONTENT_EXIT         1012
#define IDC_EDIT_ENTRYPOINT             1013
#define IDC_EDIT_IMAGEBASE              1014
#define IDC_EDIT_IMAGESIZE              1015
#define IDC_EDIT_CODEBASE               1016
#define IDC_EDIT_DATABASE               1017
#define IDC_EDIT_RAWALIGNMENT           1018
#define IDC_EDIT_FLAG                   1019
#define IDC_EDIT_FILEALIGEMENT          1020
#define IDC_STATIC3                     1021
#define IDC_STATIC4                     1022
#define IDC_STATIC5                     1023
#define IDC_STATIC6                     1024
#define IDC_STATIC7                     1025
#define IDC_STATIC8                     1026
#define IDC_EDIT_SUBSYSTEM              1027
#define IDC_EDIT_EXPORTTABLE            1027
#define IDC_EDIT_SECTIONNUM             1028
#define IDC_EDIT_IMPORTTABLE            1028
#define IDC_EDIT_TIMEFLAG               1029
#define IDC_EDIT_RESOURCE               1029
#define IDC_EDIT_HEADERSIZE             1030
#define IDC_EDIT_EXCEPTION              1030
#define IDC_EDIT_CHARACTERISTIC         1031
#define IDC_EDIT_SECURITY               1031
#define IDC_EDIT_CHECKSUM               1032
#define IDC_EDIT_RELOCATE               1032
#define IDC_EDIT_RVANUM                 1033
#define IDC_EDIT_DEBUG                  1033
#define IDC_EDIT_FOPTHEADERSIZE         1034
#define IDC_EDIT_COPYRIGHT              1034
#define IDC_STATIC11                    1035
#define IDC_EDIT_GLOBALPOINT            1035
#define IDC_STATIC12                    1036
#define IDC_EDIT_TLSTABLE               1036
#define IDC_STATIC13                    1037
#define IDC_EDIT_LOADCONF               1037
#define IDC_STATIC14                    1038
#define IDC_EDIT_INPUTRANGE             1038
#define IDC_STATIC15                    1039
#define IDC_EDIT_IAT                    1039
#define IDC_STATIC16                    1040
#define IDC_EDIT_DELAYEDINPUT           1040
#define IDC_EDIT_COM                    1041
#define IDC_EDIT_RESERVED               1042
#define IDC_STATIC_CONTENT_RVA          1043
#define IDC_BUTTON_CONTENT_EXPORT       1044
#define IDC_BUTTON_CONTENT_IMPORT       1045
#define IDC_BUTTON_CONTENT_RESOURCE     1046
#define IDC_LIST_SECTION                1046
#define IDC_BUTTON_EXPORTTABLE_EXIT     1047
#define IDC_EDIT_EXPORTTABLE_OFFSET     1048
#define IDC_EDIT_EXPORTTABLE_CHARARISTIC 1049
#define IDC_EDIT_EXPORTTABLE_BASE       1050
#define IDC_EDIT_EXPORTTABLE_NAME       1051
#define IDC_EDITEXPORTTABLE_DTRNAME     1052
#define IDC_BUTTON_CONTENT_RELOCATE     1053
#define IDC_EDIT_EXPORTTABLE_FUNCNUM    1053
#define IDC_BUTTON_CONTENT_DEBUG        1054
#define IDC_EDIT_EXPORTTABLE_FUNCNAMENUM 1054
#define IDC_BUTTON_CONTENT_COPYRIGHT    1055
#define IDC_EDIT_EXPORTTABLE_FUNCADDRESS 1055
#define IDC_EDIT_EXPORTTABLE_FUNCNAMEADDRESS 1056
#define IDC_BUTTON_CONTENT_TLS          1057
#define IDC_EDIT_EXPORTTABLE_FUNCNAMEORDERADDRESS 1057
#define IDC_LIST_EXPORTTABLE            1058
#define IDC_BUTTON_CONTENT_IMPORTRANGE  1059
#define IDC_LIST_IMPORTTABLE_UP         1059
#define IDC_EDIT_EXPORTTABLE2           1060
#define IDC_LIST_IMPORTTABLE_DOWN       1060
#define IDC_EDIT_IMPORTTABLE2           1061
#define IDC_BUTTON_IMPORTTABLE_EXIT     1061
#define IDC_EDIT_RESOURCE2              1062
#define IDC_LIST_RELOCATETABLE_DOWN     1062
#define IDC_EDIT_EXCEPTION2             1063
#define IDC_LIST_RELOCATETABLE_UP       1063
#define IDC_EDIT_SECURITY2              1064
#define IDC_EDIT_RELOCATE2              1065
#define IDC_BUTTON_RELOCATETABLE_EXIT   1065
#define IDC_EDIT_DEBUG2                 1066
#define IDC_BUTTON_ADDSHELL             1066
#define IDC_EDIT_COPYRIGHT2             1067
#define IDC_BUTTON_TARGETCODE           1067
#define IDC_EDIT_GLOBALPOINT2           1068
#define IDC_BUTTON_SHELLCODE            1068
#define IDC_EDIT_TLSTABLE2              1069
#define IDC_BUTTON_SHELL_EXIT           1069
#define IDC_EDIT_LOADCONF2              1070
#define IDC_EDIT_TARGET                 1070
#define IDC_EDIT_INPUTRANGE2            1071
#define IDC_EDIT_SHELL                  1071
#define IDC_EDIT1                       1071
#define IDC_EDIT_INPUTNAME              1071
#define IDC_EDIT_IAT2                   1072
#define IDC_BUTTON_INPUTNAME_OK         1072
#define IDC_EDIT_DELAYEDINPUT2          1073
#define IDC_EDIT_COM2                   1074
#define IDC_EDIT_RESERVED2              1075
#define IDC_BUTTON_CONTENT_COM          1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
